### ISSUE TITLE
Feature: optionally scrobble album artist

### ISSUE THREAD

**Issue by ghost** [rurza/NepTunes-Issues#50]
Also scrobble the album artist if it's different from the track artist. This might be helpful in case of compilations, soundtracks and the like.

Parameter `albumArtist` is optional according to the last.fm API documentation.

**Comment by rurza** [comment]
Cool idea :)

**Comment by dv8godd** [comment]
I'd really like this as well.  I often put "featured" musicians in the display artist field (example: "UNKLE [Featuring Gavin Clark]") because it makes more sense to me to put featured musicians with the artist than hiding them in a comments field or putting them with the song.  I DO, however, keep the albumArtist associated with the base act (so the aforementioned example would still have an albumArtist of "UNKLE").

Currently, my scrobbles on artists like UNKLE, Delerium, Prodigy, etc who regularly feature outside vocal talent get scrobbled incorrectly due to my naming conventions.  This option seems like it would fix my problem completely.

If you get the chance, please see if you can get this in a future update!  Thanks!

**Comment by rurza** [comment]
@dv8godd Thanks for the feedback. I’m waiting for the new computer and I’m going to release updated NepTunes with this feature :)

**Comment by rurza** [comment]
Hey guys!
@dv8godd @joeploijens 
I'm digging into this feature – there is a problem with Last.fm API. It seems that albumArtists parameter is ignored (maybe it's used for finding the track in their database?). 
Anyway my tracks with album artist are visible as scrobbled with artist name (instead od album artists). I could replace the artist with albumArtist if they're different but only when user selected proper option in the app preferences. Is it okay?

**Comment by dv8godd** [comment]
I think that is good for me.  I use "artist" as more of a "display artist" personally, with "album artist" being the master that keeps my library organized.  The only thing I'd add is to be sure if "album artist" is null to use "artist" (as iTunes does for organization as well).  I know, that's probably pretty obvious.  Just for reference, here's 3 different common occurrences that I run into in my own library...

Standard Track (artist populated, album artist is null), example:
  song: Age of Consent
  artist: New Order
  album: Power, Corruption & Lies
  album artist: (null)

Track with Guest Artist (both artist and album artist populated, with iTunes using album artist to keep tracks organized on the HD... and I believe this being the specific new case dealt with here), example:
  song: Reign
  artist: UNKLE [Featuring Ian Brown]
  album: Never, Never, Land
  album artist: UNKLE

Compilation Tracks (which probably shouldn't have album artist anyway as they are filed on the system differently), example:
  song: Soul of a Man
  artist: Blind Willie Johnson
  album: Martin Scorsese Presents the Blues: Soul of a Man
  album artist: (null)

For my cases, I think you're right... if artist and album artist are different (and album artist is not null) then submit album artist instead of artist.  And I'm more than happy to check any number of checkboxes that make sense and don't mess up other users to do so.

And thank you again for looking into this!

**Comment by dv8godd** [comment]
Oh, there is one other time when my "album artist" and "artist" diverge that doesn't track with the above...

I put something like "Prodigy, The" in album artist for bands to properly alphabetize in my iTunes library and still leave "The Prodigy" in artist.  I'm not sure if last.fm handles that properly, though I'd hope they do.  If they do: great.  If they don't: I don't want to complicate your life further by having to deal with that too... I'd sooner change my own library organization if it came to that.

**Comment by ghost** [comment]
Please don't replace the track artist with the album artist if they differ. It shouldn't be this "complicated". The album artist is just additional information for Last.fm which they can use to link the scrobbled track to the correct track and album in their catalog. I would just extend the current scrobble with the album artist if the album artist is not null and differs from the track artist.

Anyway, thank you for looking into this.

**Comment by rurza** [comment]
@dv8godd 
First of all, you don't have to replace article – iTunes sorts the music by ignoring them. 

<img width="401" alt="screen shot 2018-09-06 at 16 40 00" src="https://user-images.githubusercontent.com/2467137/45164797-96349d80-b1f3-11e8-943b-e2637e9ac24e.png">
<img width="380" alt="screen shot 2018-09-06 at 16 40 17" src="https://user-images.githubusercontent.com/2467137/45164801-9896f780-b1f3-11e8-897f-0612c7c782b6.png">

Second, your albums seems fine but I've encountered multiple albums, where album artist is "Various Artists". Clearly we don't want to scrobble it as an artist.

Summary: I'll add album artist info if it exists to albumArtist parameter in Last.fm API request. There won't be any switch to toggle it. :)

**Comment by dv8godd** [comment]
@rurza 
Thanks, and understood.  Though I still replace the article in Album Artist, not for iTunes benefit, but for my file system.  I don't want the Finder sorting by "The " when i go looking for tracks to pull out for a mix or the like. 

This is also a bit of a legacy of having used iTunes for 17 years.  It didn't always sort properly, so I had to deal with articles myself way back.  My library may be a bit of a hodgepodge of that legacy, though I'm working through the 160k tracks as necessary.

**Comment by hostep** [comment]
@dv8godd, this doesn't really add something to this issue, but here is maybe a little hint for you.

If you use [MusicBrainz's Picard](https://picard.musicbrainz.org/) for tagging your music (super awesome tool btw!), they add an `Album Artist Sort Order` and `Artist Sort Order` field to the ID3 tags, which I think music players recognises and sort the artists by. For example:

<img width="373" alt="musicbrainz-tagging" src="https://user-images.githubusercontent.com/85479/45234734-e0427f80-b2d6-11e8-8e32-cc910ed7db27.png">

You could maybe use those fields instead of "misusing" the `Album Artist` field?
